### ISSUE TITLE
Contact integration

### ISSUE THREAD

**Issue by Thewisergroup** [ringcentral/redtail-embeddable-ringcentral-phone#22]
We have installed the extension. We also authorized it to access the contacts in Redtail. When a known contact calls in it does not pull up their contact info. Did we miss a step during setup? Or is this as designed?

**Comment by zxdong262** [comment]
Hi @Thewisergroup,

It is not supposed to happen. So how many contacts do you have? what is the format of the phone number? How about outbound calls, would it trigger contact info panel pop up?

**Comment by zxdong262** [comment]
Did the contact match the other contact in other group @Thewisergroup

**Comment by Thewisergroup** [comment]
I am not sure what you mean by “contact”. Are referring to the phone number format?

**Comment by zxdong262** [comment]
Yes

**Comment by Thewisergroup** [comment]
Here is what shows in RingCentral and Redtail. They look the same to me.


[cid:image001.png@01D4B70A.90582A00]

[cid:image002.png@01D4B70A.90582A00]


Chris O’Brien
Customer Engineer
============================
Corporate Technologies LLC
1595 Galbraith Ave. S.E. | Grand Rapids, MI  49546
616.464.9733 (direct) | 639733 (internal)
chris.o’brien@gocorptech.com<mailto:chris.o'brien@gocorptech.com>
[cid:image003.jpg@01D11E21.B5F45DE0]

**Comment by zxdong262** [comment]
Hi @Thewisergroup  Can't see images from your email.

**Comment by Thewisergroup** [comment]
Here you go try this file.

The top image is RingCentral and the bottom Redtail.

**Comment by Thewisergroup** [comment]
Just checking to see if you received the PDF I sent that showed the RingCentral app and the Redtail app formats for the phone numbers.

Also I turned off developer mode in the Chrome extensions after installing the extension. Should it left in developer mode?


Chris O’Brien
Customer Engineer
============================
Corporate Technologies LLC
1595 Galbraith Ave. S.E. | Grand Rapids, MI  49546
616.464.9733 (direct) | 639733 (internal)
chris.o’brien@gocorptech.com<mailto:chris.o'brien@gocorptech.com>
[cid:image003.jpg@01D11E21.B5F45DE0]

**Comment by zxdong262** [comment]
Hi @Thewisergroup

I never disabled the developer mode, not sure why this happens, I may check this later.

**Comment by Thewisergroup** [comment]
Is it possible we are just using it incorrectly? Or that something in RingCentral is not turned on or off?

We have the RingCentral program running on the PC and Redtail is up and logged in.

**Comment by zxdong262** [comment]
I released new version, still can not reproduce this issue.

**Comment by Thewisergroup** [comment]
Can I just download it again to get the new version?

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by zxdong262** [comment]
https://github.com/ringcentral/redtail-embeddable-ringcentral-phone/releases/tag/v0.3.0

@Thewisergroup

**Comment by Thewisergroup** [comment]
I cannot get this extension to install in Chrome. Says manifest file missing. The old version still installs properly by going to the /dist subfolder.

**Comment by zxdong262** [comment]
@Thewisergroup How about the 0.3.1 https://github.com/ringcentral/redtail-embeddable-ringcentral-phone/releases/tag/v0.3.1 I confirmed it works in my Chrome

**Comment by CorpTech-ZP** [comment]
zxdong. I have worked with an employee of this company.  We have 0.3.3 installed, and as far as I know, working correctly.   They are asking if a specific function is part of this program.  Specifically, contact information popping up in some way when a call is received.  
 
For example, when John Smith calls Ring Central (or the Redtail Embedded app), they would like for his contact information in Redtail to popup in some way so that while the phone is ringing, they can see all of the contact's information without having to search for them.  Is this a function of the Redtail software?  If not, could it be integrated for some form of compensation?

**Comment by zxdong262** [comment]
@CorpTech-ZP Yes, that is already part of the extension, you can try it to confirm.

**Comment by zxdong262** [comment]
@CorpTech-ZP there is a screenshot for this feature, you can see it from https://www.ringcentral.com/apps/redtail-crm

**Comment by CorpTech-ZP** [comment]
Thank you for the reply.  I will look into this further.

**Comment by Thewisergroup** [comment]
Is there a specific setup for RingCentral and or Redtail that needs to be implemented for this to allow integration to the Redtail contact database? I believe we have default settings for both programs but the incoming calls do not trigger Redtail to open the users contact information.

Can you provide any setup information regarding Redtail or RingCentral?

Thank you.


Chris O’Brien
Customer Engineer
============================
Corporate Technologies LLC
1595 Galbraith Ave. S.E. | Grand Rapids, MI  49546
616.464.9733 (direct) | 639733 (internal)
chris.o’brien@gocorptech.com<mailto:chris.o'brien@gocorptech.com>
[cid:image003.jpg@01D11E21.B5F45DE0]

**Comment by CorpTech-ZP** [comment]
I appreciate your help Zhao.  I have just a few more questions. 

1. When using the Ring Central Embeddable application, under Settings>Calling> which option should we be using?  Browser, Ring Central Phone, or Ring Central for Desktop?  

2.  Our user is signing in with one phone number 555-5555, and 555-5555 is our chosen number in settings, but when opening settings, at the bottom it says "999-9999 logout."  I believe our issue is related to the fact that 999-9999 is a shared number.  Why is ring central embeddable logging in with the 999-9999 number or where is it pulling that from?

Thank you

**Comment by zxdong262** [comment]
@embbnux, can you answer @CorpTech-ZP's question?

**Comment by zxdong262** [comment]
@Thewisergroup When you click the contact list from RingCentral widgets, it will open auth button for you, after auth, RingCentral widgets will be able to access redtail's contact data, then incoming call will trigger the popup. You may check the video from https://www.ringcentral.com/apps/redtail-crm, it shows the process.

**Comment by embbnux** [comment]
Hi, @CorpTech-ZP 

For first question:
* Browser option allows user to make and receive call using browser with microphone and speaker. 
* RingCentral Desktop option will let user to use RingCentral for Desktop app when user creates a call in widget dial. 
* My RingCentral Phone option is to make calls using user's RingCentral Phone. For the call user makes, user's RingCentral phone will ring first then the party user called.  [Here](https://support.ringcentral.com/articles/en_US/RC_Knowledge_Article/87?r=5&other.SupportCommunityImage.getPictures=1&other.SupportCommunityKnowledge.getKnowledgeInfo=1&ui-comm-runtime-components-aura-components-siteforce-qb.Quarterback.validateRoute=1&ui-communities-components-aura-components-forceCommunity-seoAssistant.SeoAssistant.getSeoData=1) is introduction about it.
You can get detail information when you click `i` icon in widget's calling setting page.

For second question, now we use main number and extension number to identify user. Agree with you, it will be confused if it is different with login number. Will talk to PM about this.

Thanks

**Comment by Thewisergroup** [comment]
Is there someone we can contact in the USA that has this program working?

**Comment by zxdong262** [comment]
Hi @Thewisergroup Can you describe which part do not work? and can you post a screenshot of the chrome console log when it do not work as expected?

**Comment by zxdong262** [comment]
@Thewisergroup Can you try the latest release?

**Comment by zxdong262** [comment]
Has been a while, close it now
