### ISSUE TITLE
Incomplete contact sync

### ISSUE THREAD

**Issue by Dhollins** [ringcentral/redtail-embeddable-ringcentral-phone#27]
Only Redtail contacts beginning with A and B loaded into the RingCentral phone app.
[Network HAR.zip](https://github.com/ringcentral/redtail-embeddable-ringcentral-phone/files/3203295/Network.HAR.zip)

**Comment by zxdong262** [comment]
@Dhollins Thank for the feedback, let me check this.

**Comment by zxdong262** [comment]
@Dhollins Seems you export only XHR request? the contacts fetching actually is html request, you need catch ALL network request.

**Comment by Dhollins** [comment]
After “authorizing” RingCentral in RedTail – it shows “Registered”.  That part seems to be working fine.

Then you click “Sync Contacts”.    It says “Fetching contacts”.  I don’t the option to make any specific type of request.  It comes back and says “Done”, but only the contacts beginning with A and a portion of those beginning with B show up in the Embeddable RingCentral Phone app.

 

I’d like to talk with someone today so we can walk through this together and get it taken care of.

Is there a phone number I can call to talk with you or another representative there?

 

Thank you for your assistance!

Diane Hollins

Baumoel & Goodman Financial Strategies

3603 Brambleton Avenue

Suite C

Roanoke, VA 24018

Tel. 540-774-1452

Fax 540-774-0990

Email:  <mailto:admin@bandgstrategies.com> admin@bandgstrategies.com

Website:  <http://www.bandgstrategies.com/> www.bandgstrategies.com

 

Securities and investment advisory services offered through SagePoint Financial, Inc., member FINRA and SIPC. and Registered Investment Advisers. Fixed and Traditional insurance products offered through Baumoel & Goodman Insurance and Financial Strategies. Baumoel & Goodman Insurance and Financial Strategies is not affiliated with SagePoint Financial, Inc. or registered as a broker/dealer or investment advisor. Baumoel & Goodman Financial Strategies does not accept time-sensitive or action oriented messages delivered via e-mail, including authorization to "buy" or "sell" a security or instruction

 

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential, proprietary, and/or privileged material.  Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon this information by persons or entities other than the intended recipient is prohibited.  If you received this in error, please contact the sender and delete the material from all computers.

**Comment by zxdong262** [comment]
Sure, I can set a meeting, what is your timezone? And how many contacts do you have? How many contacts in A/B initials? @Dhollins

**Comment by Dhollins** [comment]
Total RedTail Contacts:  1114

A:  70

B:  116, but not all the B’s synced

 

We are in Virginia (USA), Eastern time zone

 

I work Tuesday, Wednesday, and Thursday.  

8:30 am – 5:00 pm

 

If you have anything available today, that would be wonderful!

 

Thanks,

Diane

 

Baumoel & Goodman Financial Strategies

3603 Brambleton Avenue

Suite C

Roanoke, VA 24018

Tel. 540-774-1452

Fax 540-774-0990

Email:  <mailto:admin@bandgstrategies.com> admin@bandgstrategies.com

Website:  <http://www.bandgstrategies.com/> www.bandgstrategies.com

 

Securities and investment advisory services offered through SagePoint Financial, Inc., member FINRA and SIPC. and Registered Investment Advisers. Fixed and Traditional insurance products offered through Baumoel & Goodman Insurance and Financial Strategies. Baumoel & Goodman Insurance and Financial Strategies is not affiliated with SagePoint Financial, Inc. or registered as a broker/dealer or investment advisor. Baumoel & Goodman Financial Strategies does not accept time-sensitive or action oriented messages delivered via e-mail, including authorization to "buy" or "sell" a security or instruction

 

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential, proprietary, and/or privileged material.  Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon this information by persons or entities other than the intended recipient is prohibited.  If you received this in error, please contact the sender and delete the material from all computers.

**Comment by zxdong262** [comment]
@Dhollins Let me set a meeting next week then, before that,  I will try to simulate your situation(create like sevral hundreds of contacts in my test account), maybe I can reproduce the bug and fix it.

**Comment by Dhollins** [comment]
Great, thanks.

Call we schedule a phone call for Tuesday, May 28th?

 

Diane Hollins

Baumoel & Goodman Financial Strategies

3603 Brambleton Avenue

Suite C

Roanoke, VA 24018

Tel. 540-774-1452

Fax 540-774-0990

Email:  <mailto:admin@bandgstrategies.com> admin@bandgstrategies.com

Website:  <http://www.bandgstrategies.com/> www.bandgstrategies.com

 

Securities and investment advisory services offered through SagePoint Financial, Inc., member FINRA and SIPC. and Registered Investment Advisers. Fixed and Traditional insurance products offered through Baumoel & Goodman Insurance and Financial Strategies. Baumoel & Goodman Insurance and Financial Strategies is not affiliated with SagePoint Financial, Inc. or registered as a broker/dealer or investment advisor. Baumoel & Goodman Financial Strategies does not accept time-sensitive or action oriented messages delivered via e-mail, including authorization to "buy" or "sell" a security or instruction

 

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential, proprietary, and/or privileged material.  Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon this information by persons or entities other than the intended recipient is prohibited.  If you received this in error, please contact the sender and delete the material from all computers.

**Comment by zxdong262** [comment]
@Dhollins I have sent you the meeting link to admin@bandgstrategies.com, if the time is not OK, you suggest another one.

**Comment by zxdong262** [comment]
@Dhollins Confirmed, it is a bug, just as you experienced, I will fix it right now and release a new version, thank you for the feedback!

**Comment by zxdong262** [comment]
Released, https://github.com/ringcentral/redtail-embeddable-ringcentral-phone/releases/tag/v0.5.0

Please try this. @Dhollins

**Comment by Dhollins** [comment]
I haven’t had time to install the new version you sent me.  I hope to do that first thing tomorrow (Wednesday) and will let you know how that goes before we schedule a new time.

 

Thanks,

Diane

**Comment by Dhollins** [comment]
Good morning.

I installed the new version using the link you emailed to me, (V 5.0)

That loaded all the contacts, so that part is now working.

I will do a little experimenting with it this morning and see how the pop-up works (opening up the RedTail contact’s page when a call comes in from them.)

 

I’ll suggest a new meeting time for Thursday morning so we can discuss any questions I have going forward.

Thanks for your assistance,

Diane

 

From: Admin [mailto:admin@bandgstrategies.com] 
Sent: Tuesday, May 28, 2019 4:20 PM
To: 'ringcentral/redtail-embeddable-ringcentral-phone' <reply@reply.github.com>
Subject: RE: [ringcentral/redtail-embeddable-ringcentral-phone] Incomplete contact sync (#27)

 

I haven’t had time to install the new version you sent me.  I hope to do that first thing tomorrow (Wednesday) and will let you know how that goes before we schedule a new time.

 

Thanks,

Diane

**Comment by MisterEHahn** [comment]
@zxdong262 

I have installed version 0.5.1

My contact sync is incomplete. Syncs only until G. 

I have 500 contacts in total, and maybe only 300 with phone numbers.

any thoughts?

**Comment by zxdong262** [comment]
Did you wait until contacts sync finish? please confirm.

**Comment by MisterEHahn** [comment]
@zxdong262 yes, I waited for sync to complete. I tried multiple times to re-sync

**Comment by zxdong262** [comment]
@MisterEHahn Any errors in browser console? How did you resync, click the "YES"?

**Comment by MisterEHahn** [comment]
Unsure if there are errors in browser console, and yes I resync by clicking yes. 

Also, I tried by deauthorzing and then authorizing again.

**Comment by Josh12949** [comment]
Hello, I just loaded this extension and it did not sync all of my contacts.  I uninstalled and reinstalled, and it still did not work.

**Comment by zxdong262** [comment]
Has been a while, close it now
