### ISSUE TITLE
Sync is incomplete

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/redtail-embeddable-ringcentral-phone#28]
@zxdong262 

I have installed version 0.5.1

My contact sync is incomplete. Syncs only until G. 

I have 500 contacts in total, and maybe only 300 with phone numbers.

any thoughts?

UPDATE - here are some error messages showing in the chrome extension manager:

![2019-06-19_15-29-23](https://user-images.githubusercontent.com/52011716/59794537-2f2a3600-92a7-11e9-9b5d-b58cf374f427.png)

_Originally posted by @MisterEHahn in https://github.com/ringcentral/redtail-embeddable-ringcentral-phone/issues/27#issuecomment-503703440_

**Comment by zxdong262** [comment]
Let's talk about it in a new thread. @MisterEHahn Can you do a meeting with me now?

**Comment by MisterEHahn** [comment]
No I can’t at the moment. Perhaps tomorrow, can you let me know a time that works

**Comment by zxdong262** [comment]
Hi @MisterEHahn, you can choose a time next week, just give me a time and your time zone, I will send you the meeting link.

**Comment by MisterEHahn** [comment]
How about next Monday at 8am EST in the US. If you are in China that will be 8pm. Let me know if this is ok for you.

**Comment by zxdong262** [comment]
@MisterEHahn Sorry for the delay, I set the meeting as you described, sended meeting link to ehahn@nscadvisor.com, Feel free to set another time if you needed.

**Comment by MisterEHahn** [comment]
Sorry having computer issues. Rebooting and trying to login now


________________________________

**Comment by MisterEHahn** [comment]
Ok I am in.

**Comment by zxdong262** [comment]
Close it now.
