### ISSUE TITLE
Hello, I just loaded this extension and it did not sync all of my contacts.  I uninstalled and reinstalled, and it still did not work.

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/redtail-embeddable-ringcentral-phone#29]
Hello, I just loaded this extension and it did not sync all of my contacts.  I uninstalled and reinstalled, and it still did not work.

_Originally posted by @Josh12949 in https://github.com/ringcentral/redtail-embeddable-ringcentral-phone/issues/27#issuecomment-526792869_

**Comment by zxdong262** [comment]
Hi @Josh12949,

How many contacts do you have? Did you see a notification says sync contacts finish?

**Comment by Josh12949** [comment]
I have about 650 contacts.  It did say sync contacts finished

**Comment by zxdong262** [comment]
@Josh12949 I added 650 contacts to my account, and it works, so there could be some issue I do not know, if you can have a meeting with me, maybe I could find out.

**Comment by zxdong262** [comment]
Has been a while, close it now
