### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by jmlugares** [ringcentral/redtail-embeddable-ringcentral-phone#30]
Hello Team,

We are getting run time error when running redtail crm for RingCentral 

![image](https://user-images.githubusercontent.com/52936394/65364114-42e88e00-dc42-11e9-8178-56dbff5abd0b.png)

**Comment by zxdong262** [comment]
Thank you for feedback, we will look into this.

**Comment by zxdong262** [comment]
@jmlugares Sorry for the delay, fixed in latest release, you will get upgrade notification when refresh redtailCRM page.
