### ISSUE TITLE
Unable to Sync Contacts and Log Calls 

### ISSUE THREAD

**Issue by jin-fhg** [ringcentral/redtail-embeddable-ringcentral-phone#33]
Hello @zxdong262 

We have received a report from a RingCentral customer where they are unable to make the calls log and sync the contacts. When they click the authorize button to sync contacts, it does not seem to start the sync and when we make an outbound call we cannot even manually log it. Please see the attached video: 

https://drive.google.com/file/d/1KDjc_L-nNUwStYo3fyNyq3iy9Obrj6HW/view?usp=sharing

Please let me know if you need more details.

Best Regards,
Jin

**Comment by zxdong262** [comment]
From the video, the user did not click authorize RingCentral to access RedtailCRM data button.
