### ISSUE TITLE
Persistent after auth message 

### ISSUE THREAD

**Issue by roholton** [ringcentral/redtail-embeddable-ringcentral-phone#42]
Hello team,

my client is utilizing both the google RingCentral and the RedTail CRM embedded. could this be the cause for the constant message pop-up "After auth, you can access RedtailCRM contacts from RingCentral phone's contacts list. You can revoke access from RingCentral phone's setting."

**Comment by zxdong262** [comment]
@roholton Can you check your Chrome cookie setting from chrome://settings/cookies, make sure you did **not** block third party cookie. That is the only way I can think of it will happen. Let me know if it is the issue. If it is not this issue, maybe we can have a meeting to check it.

**Comment by roholton** [comment]
Thank you. That helped. Next is we are not seeing all of the RedTail CRM contacts in RingCentral. One user goes up to the letter J another only goes to G.

Robert Holton
LPL Financial
Technology Consultant  |  Technology Solutions
Direct: (619) 600-0112<tel:(619)%20600-0112>
Email: robert.holton@lpl.com<mailto:robert.holton@lpl.com>

[Business Solutions Email Signature_v3]<https://www.lplbusinesssolutions.com/technology>

For Urgent, time-sensitive help – Call the VCTO helpdesk
(866) 529-5144<tel:(866)%20529-5144> Mon-Fri 7:30AM<detected://date/1> – 8:30pm<detected://date/2>

LPL TSHD (800) 877-7210 x6357<tel:(800)%20877-7210;6357>

**Comment by zxdong262** [comment]
@roholton It will take minutes even hours to sync all contacts, depending on how many contacts do you have, if it not all synced, you can resync, it will sync from last break point until it finished.

**Comment by zxdong262** [comment]
@roholton @mikef723 In developer console, it will show the process, it will fetch contacts page by page, can you provide screenshots of yours? Did you wait fo the syncing finish?

**Comment by mikef723** [comment]
Is this what you are looking for?  Sorry, I'm an end user not a developer.

![Annotation 2020-08-25 085527](https://user-images.githubusercontent.com/70021227/91176863-dfb47680-e6b0-11ea-8fc4-13badaf477e9.jpg)
![Annotation 2020-08-25 081723](https://user-images.githubusercontent.com/70021227/91176871-e216d080-e6b0-11ea-95fe-4e0ea6ab90cb.jpg)

**Comment by zxdong262** [comment]
@mikef723 Can we have a meeting to check it? if you can, please send email to drake.zhao@ringcentral.com with your available time and timezone(your AM time preferred), I will send you the email link.

**Comment by zxdong262** [comment]
@roholton @mikef723 

New release fixed it: https://github.com/ringcentral/redtail-embeddable-ringcentral-phone/releases/tag/v2.3.0

Thank you all for the feedback.

**Comment by roholton** [comment]
Awesome thank you for the update. I’ll reach out to the client to implement the update.

Robert Holton
LPL Financial
Technology Consultant  |  Technology Solutions
Direct: (619) 600-0112<tel:(619)%20600-0112>
Email: robert.holton@lpl.com<mailto:robert.holton@lpl.com>

[Business Solutions Email Signature_v3]<https://www.lplbusinesssolutions.com/technology>

For Urgent, time-sensitive help – Call the VCTO helpdesk
(866) 529-5144<tel:(866)%20529-5144> Mon-Fri 7:30AM<detected://date/1> – 8:30pm<detected://date/2>

LPL TSHD (800) 877-7210 x6357<tel:(800)%20877-7210;6357>

We take care of our advisors so they can take care of their clients.
