### ISSUE TITLE
Only allow one instance of ring central per active browser and If possible static so the extension doesn't reload when clicking on different pages in Redtail

### ISSUE THREAD

**Issue by adambrill89** [ringcentral/redtail-embeddable-ringcentral-phone#50]
When using Redtail frequently you must move to other web pages to get account info. The sync does not actively continue where it left off which causes one to have to restart the process all over sometimes wiping away all sync contacts. 

I suggest writing a script that only allows a single instance of the ring central extension to run per a browser as having more than one window of Redtail running in the same browser causes issues with the application that interrupts logging calls, syncing, and creates random error messages.

During my work flow like most Redtail users, I tend have ring central syncing constantly on a single page and another page to actively log calls and complete tasks but I noticed that by clicking to each separate window starts  the web phone activation which I believe may have something to do with the issues.

The other alternative is use 1 Redtail page in chrome and 1 Redtail page in edge and that appears to be more stable when working with more than one instance of Redtail.

Let me know how I can be of assistance, I really need this to get fixed in order to roll out to other users.

**Comment by zxdong262** [comment]
@adambrill89 It will sync from last break page if you try sync all contacts after reload, also when switch tab, the inactive tab will detatch phone session, keep only current tab phone session active, becasue we have a 5 session limit for one user.

Hope this clear things for you, let me know if you have other issues.
